package br.com.imix.view;

import java.awt.Graphics;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class AreaTrabalho extends javax.swing.JFrame {
    
    public String usuarioLogado;
    public String perfilLogado;

    public AreaTrabalho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imgFundo/Fundo_Sede.png"));
        Image image = icon.getImage();
        painelDesktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(), this);
            }
        };
        painelStatus = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        menUsuario = new javax.swing.JMenu();
        cadUsuario = new javax.swing.JMenuItem();
        listaUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        menAluno = new javax.swing.JMenu();
        cadAluno = new javax.swing.JMenuItem();
        listaAluno = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menSair = new javax.swing.JMenu();
        sairSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Área de Trabalho");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(798, 454));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        painelStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Logado por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Usuário:");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 255));
        lblUsuario.setText("João da Silva");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Perfil:");

        lblPerfil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPerfil.setForeground(new java.awt.Color(0, 0, 255));
        lblPerfil.setText("ADM");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Data Atual:");

        lblData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblData.setForeground(new java.awt.Color(0, 0, 255));
        lblData.setText("Data");

        javax.swing.GroupLayout painelStatusLayout = new javax.swing.GroupLayout(painelStatus);
        painelStatus.setLayout(painelStatusLayout);
        painelStatusLayout.setHorizontalGroup(
            painelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelStatusLayout.setVerticalGroup(
            painelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelStatusLayout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(painelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblData))
                    .addGroup(painelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lblPerfil))
                    .addGroup(painelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblUsuario))))
        );

        painelDesktop.setLayer(painelStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painelDesktopLayout = new javax.swing.GroupLayout(painelDesktop);
        painelDesktop.setLayout(painelDesktopLayout);
        painelDesktopLayout.setHorizontalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelDesktopLayout.setVerticalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDesktopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/285655_user_icon.png"))); // NOI18N
        menUsuario.setText("Usuários");

        cadUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        cadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/309049_add_user_human_person_plus_icon.png"))); // NOI18N
        cadUsuario.setText("Cadastro de Usuário");
        cadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadUsuarioActionPerformed(evt);
            }
        });
        menUsuario.add(cadUsuario);

        listaUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        listaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/9024061_user_list_fill_icon.png"))); // NOI18N
        listaUsuario.setText("Lista de Usuários");
        listaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaUsuarioActionPerformed(evt);
            }
        });
        menUsuario.add(listaUsuario);
        menUsuario.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/2672759_app_chart_essential_object_ui_icon.png"))); // NOI18N
        jMenuItem1.setText("Relatório de Usuários");
        menUsuario.add(jMenuItem1);

        menuPrincipal.add(menUsuario);

        menAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/9023992_student_fill_icon.png"))); // NOI18N
        menAluno.setText("Alunos(as)");

        cadAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        cadAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/6324237_knowledge_learning_education_hat_student_icon.png"))); // NOI18N
        cadAluno.setText("Cadastro de Aluno");
        cadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAlunoActionPerformed(evt);
            }
        });
        menAluno.add(cadAluno);

        listaAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        listaAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/6324229_book and pen_icon.png"))); // NOI18N
        listaAluno.setText("Lista de Alunos");
        listaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAlunoActionPerformed(evt);
            }
        });
        menAluno.add(listaAluno);
        menAluno.add(jSeparator2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/8541636_clipboard_list_icon.png"))); // NOI18N
        jMenuItem3.setText("Relatório de Alunos");
        menAluno.add(jMenuItem3);

        menuPrincipal.add(menAluno);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/1564529_mechanism_options_settings_configuration_setting_icon.png"))); // NOI18N
        jMenu1.setText("Configurações");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/9021901_user_switch_bold_icon.png"))); // NOI18N
        jMenuItem4.setText("Trocar de Usuário");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        menuPrincipal.add(jMenu1);

        menSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/10131944_door_exit_line_icon.png"))); // NOI18N
        menSair.setText("Sair");

        sairSistema.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        sairSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/7030313_sign out_ui basic_logout_app_user interface_icon.png"))); // NOI18N
        sairSistema.setText("Sair do Sistema");
        sairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairSistemaActionPerformed(evt);
            }
        });
        menSair.add(sairSistema);

        menuPrincipal.add(menSair);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDesktop)
        );

        setSize(new java.awt.Dimension(814, 493));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setExtendedState(AreaTrabalho.MAXIMIZED_BOTH);
        lblUsuario.setText(usuarioLogado);
        lblPerfil.setText(perfilLogado);
  
        Date agora = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String dataFormatada = formato.format(agora);
        lblData.setText(dataFormatada);
    }//GEN-LAST:event_formWindowActivated

    private void sairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairSistemaActionPerformed
        int confirmar = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair do sistema?","Atenção",JOptionPane.YES_NO_OPTION);
        if(confirmar == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_sairSistemaActionPerformed

    private void cadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadUsuarioActionPerformed
        FormularioUsuario fu = new FormularioUsuario();
        fu.setVisible(true);
    }//GEN-LAST:event_cadUsuarioActionPerformed

    private void cadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAlunoActionPerformed
        FormularioAluno fa = new FormularioAluno();
        fa.setVisible(true);
    }//GEN-LAST:event_cadAlunoActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja trocar de usuário?","Atenção",JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            FormularioLogin fl = new FormularioLogin();
            this.dispose();
            fl.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void listaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaUsuarioActionPerformed
        ListaUsuario listaU = new ListaUsuario();
        listaU.painelGuiasUsuario.setSelectedIndex(1);
        if(perfilLogado.equals("USUÁRIO")){
            listaU.btnEditar.setEnabled(false);
            listaU.btnExcluir.setEnabled(false);
        }
        listaU.setVisible(true);
    }//GEN-LAST:event_listaUsuarioActionPerformed

    private void listaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAlunoActionPerformed
        ListaAluno listaA = new ListaAluno();
        listaA.painelGuiasAluno.setSelectedIndex(1);
        if(perfilLogado.equals("USUÁRIO")){
            listaA.btnEditar.setEnabled(false);
            listaA.btnExcluir.setEnabled(false);
        }
        listaA.setVisible(true);
    }//GEN-LAST:event_listaAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaTrabalho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem cadAluno;
    public javax.swing.JMenuItem cadUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem listaAluno;
    private javax.swing.JMenuItem listaUsuario;
    private javax.swing.JMenu menAluno;
    private javax.swing.JMenu menSair;
    private javax.swing.JMenu menUsuario;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JDesktopPane painelDesktop;
    private javax.swing.JPanel painelStatus;
    private javax.swing.JMenuItem sairSistema;
    // End of variables declaration//GEN-END:variables
}
