package br.com.imix.view;

import br.com.imix.dao.AlunoDAO;
import br.com.imix.dao.CursoDAO;
import br.com.imix.dao.DiasSemanaDAO;
import br.com.imix.dao.HorarioDAO;
import br.com.imix.model.Aluno;
import br.com.imix.model.Curso;
import br.com.imix.model.DiasSemana;
import br.com.imix.model.Horario;
import br.com.imix.utilitarios.Utilitarios;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ListaAluno extends javax.swing.JFrame {

    public void listar(){
        AlunoDAO aDAO = new AlunoDAO();
        List<Aluno> lista = aDAO.listar();
        DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
        dados.setNumRows(0);
        for(Aluno a : lista){
            dados.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getCelular(),
                a.getCurso(),
                a.getModulo(),
                a.getDias_semana(),
                a.getHorario()
            });
        }
    }

    public ListaAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTopo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        painelGuiasAluno = new javax.swing.JTabbedPane();
        painelDadosAluno = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        cbHorarios = new javax.swing.JComboBox();
        txtNome = new javax.swing.JTextField();
        txtModulo = new javax.swing.JTextField();
        cbCurso = new javax.swing.JComboBox();
        txtCelular = new javax.swing.JFormattedTextField();
        lblUsuario = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblNome2 = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblDiasSemana = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        cbDiasSemana = new javax.swing.JComboBox();
        lblModulo = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        painelConsultaAluno = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtPesquisaNome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        lblTotalAluno = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        painelConsultaDiasHorario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaFiltrada = new javax.swing.JTable();
        cbFiltrarDias = new javax.swing.JComboBox();
        cbFiltrarHorario = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        lblQtdAluno = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Usuários");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        painelTopo.setBackground(new java.awt.Color(153, 0, 0));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Lista de Alunos(as)");

        javax.swing.GroupLayout painelTopoLayout = new javax.swing.GroupLayout(painelTopo);
        painelTopo.setLayout(painelTopoLayout);
        painelTopoLayout.setHorizontalGroup(
            painelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelTopoLayout.setVerticalGroup(
            painelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        txtId.setEnabled(false);

        cbHorarios.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbHorariosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        cbCurso.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbCursoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsuario.setText("Usuário:");

        lblId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblId.setText("ID:");

        lblNome2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNome2.setText("Nome:");

        lblCurso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCurso.setText("Curso:");

        lblCelular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCelular.setText("Celular:");

        lblDiasSemana.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDiasSemana.setText("Dias/Semana:");

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSenha.setText("Senha:");

        cbDiasSemana.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbDiasSemanaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblModulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblModulo.setText("Módulo:");

        lblHorario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHorario.setText("Horário:");

        javax.swing.GroupLayout painelDadosAlunoLayout = new javax.swing.GroupLayout(painelDadosAluno);
        painelDadosAluno.setLayout(painelDadosAlunoLayout);
        painelDadosAlunoLayout.setHorizontalGroup(
            painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosAlunoLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosAlunoLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(painelDadosAlunoLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNome2)
                                .addComponent(lblId))
                            .addGap(5, 5, 5)
                            .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelDadosAlunoLayout.createSequentialGroup()
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 299, Short.MAX_VALUE))
                                .addComponent(txtNome))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosAlunoLayout.createSequentialGroup()
                                    .addComponent(lblModulo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(painelDadosAlunoLayout.createSequentialGroup()
                                    .addComponent(lblCurso)
                                    .addGap(7, 7, 7)))
                            .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbCurso, 0, 227, Short.MAX_VALUE)
                                .addComponent(txtModulo)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadosAlunoLayout.createSequentialGroup()
                            .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelDadosAlunoLayout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(lblCelular))
                                .addComponent(lblUsuario))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(167, 167, 167)
                            .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDiasSemana)
                                .addComponent(lblHorario))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbDiasSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        painelDadosAlunoLayout.setVerticalGroup(
            painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosAlunoLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCurso))
                    .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblId)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblModulo)
                        .addComponent(txtModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNome2)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelular)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDiasSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiasSemana))
                .addGap(22, 22, 22)
                .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorario))
                .addGap(24, 24, 24)
                .addGroup(painelDadosAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        painelGuiasAluno.addTab("Dados dos(as) Alunos(as)", painelDadosAluno);

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNome.setText("Nome:");

        txtPesquisaNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaNomeKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/8723069_filter_icon.png"))); // NOI18N
        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Celular", "Curso", "Módulo", "Dias", "Horário"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        lblTotalAluno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotalAluno.setText("Total de Alunos(as):");

        lblQuantidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQuantidade.setForeground(new java.awt.Color(0, 0, 255));
        lblQuantidade.setText("Total");

        javax.swing.GroupLayout painelConsultaAlunoLayout = new javax.swing.GroupLayout(painelConsultaAluno);
        painelConsultaAluno.setLayout(painelConsultaAlunoLayout);
        painelConsultaAlunoLayout.setHorizontalGroup(
            painelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(71, 71, 71)
                .addComponent(lblTotalAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQuantidade)
                .addContainerGap(126, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        painelConsultaAlunoLayout.setVerticalGroup(
            painelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConsultaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(lblTotalAluno)
                    .addComponent(lblQuantidade))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
        );

        painelGuiasAluno.addTab("Consulta de Alunos(as)", painelConsultaAluno);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Dias Semana:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Horário:");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/9004762_search_find_zoom_magnifier_icon.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tabelaFiltrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Celular", "Curso", "Módulo", "Dias", "Horário"
            }
        ));
        tabelaFiltrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFiltradaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaFiltrada);

        cbFiltrarDias.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbFiltrarDiasAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        cbFiltrarHorario.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbFiltrarHorarioAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Qtd. Alunos(as):");

        lblQtdAluno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQtdAluno.setForeground(new java.awt.Color(0, 51, 255));
        lblQtdAluno.setText("0");

        javax.swing.GroupLayout painelConsultaDiasHorarioLayout = new javax.swing.GroupLayout(painelConsultaDiasHorario);
        painelConsultaDiasHorario.setLayout(painelConsultaDiasHorarioLayout);
        painelConsultaDiasHorarioLayout.setHorizontalGroup(
            painelConsultaDiasHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaDiasHorarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbFiltrarDias, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbFiltrarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQtdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        painelConsultaDiasHorarioLayout.setVerticalGroup(
            painelConsultaDiasHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultaDiasHorarioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(painelConsultaDiasHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btnBuscar)
                    .addComponent(cbFiltrarDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFiltrarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lblQtdAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelGuiasAluno.addTab("Consulta por Dias/Horário", painelConsultaDiasHorario);

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/216184_edit_icon.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/3844425_can_trash_icon.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/imix/imagens/326554_cancel_icon.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelTopo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelGuiasAluno)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(41, 41, 41)
                .addComponent(btnExcluir)
                .addGap(43, 43, 43)
                .addComponent(btnCancelar)
                .addGap(207, 207, 207))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnEditar, btnExcluir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelGuiasAluno)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelar, btnEditar, btnExcluir});

        setSize(new java.awt.Dimension(889, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
        
        int quantidade;
        AlunoDAO aDAO = new AlunoDAO();
        quantidade = aDAO.contarAlunos();
        lblQuantidade.setText(String.valueOf(quantidade));
    }//GEN-LAST:event_formWindowActivated

    private void txtPesquisaNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaNomeKeyReleased
        String nome = "%" + txtPesquisaNome.getText() + "%";
        AlunoDAO aDAO = new AlunoDAO();
        List<Aluno> lista = aDAO.filtrar(nome);
        DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
        dados.setNumRows(0);
        for(Aluno a : lista){
            dados.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getCelular(),
                a.getCurso(),
                a.getModulo(),
                a.getDias_semana(),
                a.getHorario()
            });
        }
    }//GEN-LAST:event_txtPesquisaNomeKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome = "%" + txtPesquisaNome.getText() + "%";
        AlunoDAO aDAO = new AlunoDAO();
        List<Aluno> lista = aDAO.filtrar(nome);
        DefaultTableModel dados = (DefaultTableModel)tabela.getModel();
        dados.setNumRows(0);
        for(Aluno a : lista){
            dados.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getCelular(),
                a.getCurso(),
                a.getModulo(),
                a.getDias_semana(),
                a.getHorario()
            });
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        painelGuiasAluno.setSelectedIndex(0);
        txtId.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        txtNome.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        txtCelular.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
        txtModulo.setText(tabela.getValueAt(tabela.getSelectedRow(), 4).toString()); 

        Curso c = new Curso();
        CursoDAO cDAO = new CursoDAO();
        c = cDAO.buscarCurso(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
        cbCurso.getModel().setSelectedItem(c);
        
        DiasSemana s = new DiasSemana();
        DiasSemanaDAO sDAO = new DiasSemanaDAO();
        s = sDAO.buscarDias(tabela.getValueAt(tabela.getSelectedRow(), 5).toString());
        cbDiasSemana.getModel().setSelectedItem(s);
        
        Horario h = new Horario();
        HorarioDAO hDAO = new HorarioDAO();
        h = hDAO.buscarHorários(tabela.getValueAt(tabela.getSelectedRow(), 6).toString());
        cbHorarios.getModel().setSelectedItem(h);
        
        AlunoDAO aDAO = new AlunoDAO();
        int id = (int) tabela.getValueAt(tabela.getSelectedRow(), 0);
        
        String usuario = aDAO.buscarUsuario(id);
        txtUsuario.setText(usuario);
        String senha = aDAO.buscarSenha(id);
        txtSenha.setText(senha);        
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Aluno a = new Aluno();
        a.setId(Integer.valueOf(txtId.getText()));
        a.setNome(txtNome.getText());
        a.setCelular(txtCelular.getText());
        a.setUsuario(txtUsuario.getText());
        a.setSenha(txtSenha.getText());
        a.setCurso((Curso)cbCurso.getSelectedItem());
        a.setModulo(txtModulo.getText());
        a.setDias_semana((DiasSemana)cbDiasSemana.getSelectedItem());
        a.setHorario((Horario)cbHorarios.getSelectedItem());
        
        AlunoDAO aDAO = new AlunoDAO();
        aDAO.editar(a);
        
        Utilitarios util = new Utilitarios();
        util.LimparTela(painelDadosAluno);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int confirmar = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o(a) aluno(a)?","Atenção", JOptionPane.YES_NO_OPTION);
        if(confirmar == JOptionPane.YES_OPTION){
            Aluno a = new Aluno();
            a.setId(Integer.valueOf(txtId.getText()));
            AlunoDAO dao = new AlunoDAO();
            dao.excluir(a);
        
            Utilitarios util = new Utilitarios();
            util.LimparTela(painelDadosAluno);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String dias    = cbFiltrarDias.getSelectedItem().toString();
        String horario = cbFiltrarHorario.getSelectedItem().toString();
        int qtdAluno = 0;
        
        AlunoDAO aDAO = new AlunoDAO();         
        List<Aluno> lista = aDAO.buscarPorDiaHorario(dias, horario);
        lblQtdAluno.setText(String.valueOf(lista.size()));
        DefaultTableModel dados = (DefaultTableModel)tabelaFiltrada.getModel();
        dados.setNumRows(0);
        for(Aluno a : lista){
            dados.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getCelular(),
                a.getCurso(),
                a.getModulo(),
                a.getDias_semana(),
                a.getHorario()
            });
            qtdAluno = dados.getRowCount();
        }
        lblQtdAluno.setText(String.valueOf(qtdAluno));
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cbFiltrarDiasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbFiltrarDiasAncestorAdded
        DiasSemanaDAO dao = new DiasSemanaDAO();
        List<DiasSemana> lista = dao.listar();
        cbFiltrarDias.removeAllItems();
        for(DiasSemana s : lista){
            cbFiltrarDias.addItem(s);
        }
    }//GEN-LAST:event_cbFiltrarDiasAncestorAdded

    private void cbFiltrarHorarioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbFiltrarHorarioAncestorAdded
        HorarioDAO dao = new HorarioDAO();
        List<Horario> lista = dao.listar();
        cbFiltrarHorario.removeAllItems();
        for(Horario h : lista){
            cbFiltrarHorario.addItem(h);
        }
    }//GEN-LAST:event_cbFiltrarHorarioAncestorAdded

    private void tabelaFiltradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFiltradaMouseClicked
        painelGuiasAluno.setSelectedIndex(0);
        txtId.setText(tabelaFiltrada.getValueAt(tabelaFiltrada.getSelectedRow(), 0).toString());
        txtNome.setText(tabelaFiltrada.getValueAt(tabelaFiltrada.getSelectedRow(), 1).toString());
        txtCelular.setText(tabelaFiltrada.getValueAt(tabelaFiltrada.getSelectedRow(), 2).toString());
        txtModulo.setText(tabelaFiltrada.getValueAt(tabelaFiltrada.getSelectedRow(), 4).toString()); 

        Curso c = new Curso();
        CursoDAO cDAO = new CursoDAO();
        c = cDAO.buscarCurso(tabelaFiltrada.getValueAt(tabelaFiltrada.getSelectedRow(), 3).toString());
        cbCurso.getModel().setSelectedItem(c);
        
        DiasSemana s = new DiasSemana();
        DiasSemanaDAO sDAO = new DiasSemanaDAO();
        s = sDAO.buscarDias(tabelaFiltrada.getValueAt(tabelaFiltrada.getSelectedRow(), 5).toString());
        cbDiasSemana.getModel().setSelectedItem(s);
        
        Horario h = new Horario();
        HorarioDAO hDAO = new HorarioDAO();
        h = hDAO.buscarHorários(tabelaFiltrada.getValueAt(tabelaFiltrada.getSelectedRow(), 6).toString());
        cbHorarios.getModel().setSelectedItem(h);
        
        AlunoDAO aDAO = new AlunoDAO();
        int id = (int) tabelaFiltrada.getValueAt(tabelaFiltrada.getSelectedRow(), 0);
        
        String usuario = aDAO.buscarUsuario(id);
        txtUsuario.setText(usuario);
        String senha = aDAO.buscarSenha(id);
        txtSenha.setText(senha);  
    }//GEN-LAST:event_tabelaFiltradaMouseClicked

    private void cbCursoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbCursoAncestorAdded
        CursoDAO cDAO = new CursoDAO();
        List<Curso> lista = cDAO.listar();
        for(Curso c : lista){
            cbCurso.addItem(c);
        }
    }//GEN-LAST:event_cbCursoAncestorAdded

    private void cbDiasSemanaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbDiasSemanaAncestorAdded
        DiasSemanaDAO dao = new DiasSemanaDAO();
        List<DiasSemana> lista = dao.listar();
        for(DiasSemana s : lista){
            cbDiasSemana.addItem(s);
        }
    }//GEN-LAST:event_cbDiasSemanaAncestorAdded

    private void cbHorariosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbHorariosAncestorAdded
        HorarioDAO dao = new HorarioDAO();
        List<Horario> lista = dao.listar();
        for(Horario h : lista){
            cbHorarios.addItem(h);
        }
    }//GEN-LAST:event_cbHorariosAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox cbCurso;
    private javax.swing.JComboBox cbDiasSemana;
    private javax.swing.JComboBox cbFiltrarDias;
    private javax.swing.JComboBox cbFiltrarHorario;
    private javax.swing.JComboBox cbHorarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDiasSemana;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblModulo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblQtdAluno;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalAluno;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel painelConsultaAluno;
    private javax.swing.JPanel painelConsultaDiasHorario;
    private javax.swing.JPanel painelDadosAluno;
    public javax.swing.JTabbedPane painelGuiasAluno;
    private javax.swing.JPanel painelTopo;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabelaFiltrada;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtModulo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisaNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
